[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/week"
  to = "/.netlify/functions/week"
  status = 200

[[redirects]]
  from = "/api/standings/*"
  to = "/.netlify/functions/standings"
  status = 200
